### ISSUE TITLE
Unable to edit saved search

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2285]
### Problem description

If I modify search query and click "Update search criteria" - it says that criteria was updated, but actualy nothing happend. And if I click "search" after query modification, Update button disapears, and there is only button "Save" like for first search. And I can't save new query with old name.
### Environment
- Graylog Version:2.0.1

**Comment by kriegaex** [comment]
This also drives me crazy. I can neither save searches which currently return no results nor edit/delete them if the result set is empty. This pollutes our namespace, having duplicates for search labels with/without typos, for identical searches with just different time frame etc. There should be a way to manage saved searches (rename, delete, edit) without the need to actually execute them and get a non-empty result.

**Comment by joschi** [comment]
@kriegaex Which version of Graylog are you using?

**Comment by kriegaex** [comment]
The front-end says: graylog-web-interface v1.3.4 (0d67a80)

BTW, I am not the administrator, just a user. But I know the former.

**Comment by joschi** [comment]
@kriegaex I recommend upgrading to the latest stable version of Graylog (which is Graylog 2.1.2 at the time of writing).

**Comment by kriegaex** [comment]
Well, @joschi, I know this is often a good idea, but I have very limited influence on that decision. Can you provide me with arguments as to why upgrading would be a good idea? Has my issue definitely been fixed in 2.1.2? This issue is listed as open.

**Comment by joschi** [comment]
@kriegaex See http://docs.graylog.org/en/2.1/pages/changelog.html for the list of changes since Graylog 1.3.4 and https://www.graylog.org/blog/ for a more "user-friendly" list.

The issue with being unable to delete saved searches with 0 search results was fixed in #2253.

**Comment by eric-tucker** [comment]
If I modify the search query I am no longer given the option to update a saved search.     It change the button to "Save Search Criteria"

Very cumbersome.

**Comment by burukuru** [comment]
I think this is still happening in 2.1.3.
I click on a saved search, modify the criteria, click "Saved search > Update search criteria". Interface confirms that changes saved, but on page reload old criteria is still there.
If I click search after modifying the criteria, the "Saved search" button changes  as described in by Eric. Saving results in an error.
Search in both cases has results.

**Comment by joschi** [comment]
@burukuru 
> I think this is still happening in 2.1.3.

That's why this issue hasn't been closed yet…

**Comment by msteelepmp** [comment]
I can confirm this issue is still happening in 2.2.3+7adc951.
The work around is to save the search under a new name and then delete the old search.

**Comment by jothoma1** [comment]
Bug still present on 2.3
Users are a bit lost as they thought there saved search were updated

**Comment by joschi** [comment]
@jothoma1 Why wouldn't it be present in Graylog 2.3.x? The issue hasn't been worked on…

**Comment by hc4** [comment]
+1 for fix to this issue.
Very annoying.

ps. sometimes bugs fixes, because of refactoring of some core components.

**Comment by jothoma1** [comment]
@joschi yes, sorry for the confusion but i just saw this as my users complain about it

**Comment by laakkus** [comment]
2.4.0 , the bug annoys still

**Comment by bernstein82** [comment]
oh my, yet another broken oss projects without any bugfixers...

**Comment by joschi** [comment]
@bernstein82 We're looking forward to your pull request to fix the issue. 👍

**Comment by iakko** [comment]
Hello @bernstein82, is there an idea about when the issue would be fixed?

**Comment by xtruthx** [comment]
Hi,  to know when the fix will be available would be nice @bernstein82.

**Comment by bernstein82** [comment]
thanks @dennisoelkers !
