### ISSUE TITLE
Unable to map LDAP groups to Graylog role - Missing plugin component 

### ISSUE THREAD

**Issue by whittle1** [Graylog2/graylog2-server#3485]
Hiya,

I have got LDAP authentication working within Graylog, and now I want to map AD groups to Graylog roles, to minimise the amount of work required to set up existing AD users with Graylog stream access.

When trying to set this up within the Graylog web interface, I get the message: 
"Plugin component missing for authenticator legacy-ldap-groups, this is an error."

This is when accessing the '/system/authentication/config/legacy-ldap-groups' URL, which is the page linked from the LDAP/Active Directory config screen within Graylog .

![gl-error](https://cloud.githubusercontent.com/assets/25746451/22887992/1745bee0-f1fc-11e6-9a0d-0e8f7bd4dee0.jpg)

Please let me know if I can provide any futher infomation.

I am running the current version of Graylog aviable from the Graylog CentOS repo (Graylog 2.2.0). I followed the instation guide below to install Graylog.
http://docs.graylog.org/en/2.2/pages/installation/os/centos.html

* Graylog Version: Graylog 2.2.0+d9681cb
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.4.2
* Operating System: CentOS 7
* Browser version: Firefox 51.0.1

**Comment by joschi** [comment]
@whittle1 I'm unable to reproduce this issue with Graylog 2.2.0.

Please attach a list of installed plugins and make sure to clear your browser cache.

**Comment by whittle1** [comment]
@joschi Thanks for the reply. I've cleared the browsed cache, and also tried in Chrome, and the problem persists.

This is the contents of the /usr/share/graylog-server/plugin/ directory. These will have been the default plugins that will have been installed with the graylog-server package from the CentOS repo.

graylog-plugin-anonymous-usage-statistics-2.2.0.jar
graylog-plugin-beats-2.2.0.jar
graylog-plugin-collector-2.2.0.jar
graylog-plugin-enterprise-integration-2.2.0.jar
graylog-plugin-map-widget-2.2.0.jar
graylog-plugin-pipeline-processor-2.2.0.jar

I've checked /var/log/graylog-server/server.log and there are no errors related to this problem.

Thanks again.

**Comment by joschi** [comment]
@whittle1 Are there any error messages in the Javascript/Developer console of your web browser?
* https://developers.google.com/web/tools/chrome-devtools/console/
* https://developer.mozilla.org/en-US/docs/Tools/Web_Console

Could you please additionally describe exactly what you're doing from log-in up to the moment you see the error message in your web browser?

Did you upgrade your Graylog installation or was this a completely fresh setup?

**Comment by jalogisch** [comment]
@whittle1 can you please give us an update on this.

we are not able to reproduce this on our end.

**Comment by whittle1** [comment]
Apologies for delay.

@joschi 
This is a completely fresh install of Graylog, on a newly created server. This morning I have updated to 2.2.1+4829190, but the problem occurred both before and after this.

The steps I am taking to view the error:
-Login as admin user
-Go to System -> Authentication
-Go to "3. LDAP Active Directory"
-Click the "mapping LDAP groups to Graylog roles" link, the majority of the way down the page.
-Receive the error "Plugin component missing for authenticator legacy-ldap-groups, this is an error".

I've attached an image of the warnings from the browser debugger when progressing through the steps above.

I've also attached the server.log file, which contains all logs between graylog startup and the problem occurring.

I have now noticed this line in the logs, I'm unsure if its related.
2017-02-21T08:39:23.143Z INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.LdapGroupMappingMigration] periodical. Not configured to run on this node. 


Thanks,
Stephen

![graylog-devcapture](https://cloud.githubusercontent.com/assets/25746451/23157683/12063f5e-f814-11e6-863d-34545d969ed7.PNG)
[graylog serverlog.txt](https://github.com/Graylog2/graylog2-server/files/789556/graylog.serverlog.txt)

**Comment by shthead** [comment]
I am also experiencing this error. I have deployed a new appliance (using the VMWare image), set up AD auth and get the same error.

**Comment by funeralium666** [comment]
Hi, I have the same error also with Graylog 2.2.1 installed on CentOS 7.3. Can't get Active Directory groups working.

**Comment by YoranSys** [comment]
Hi, I have the same error also with Graylog 2.2.1 installed on Debian 7. Can't get Active Directory groups mapping working.

**Comment by funeralium666** [comment]
Somehow I managed those LDAP groups working. The error is still there, but it's not interrupting my configuration tasks.

**Comment by pmsumner** [comment]
I am just setting up AD auth and have stumbled across this problem.  There's nothing in the server/current log file or in the Chrome console when loading $IP/system/authentication/config/legacy-ldap-groups.

Anything else I can provide that might be useful?

**Comment by Ollie42** [comment]
The same Problem here with Graylog Version v2.2.2+691b4b7 on Centos 7
Are there any Updates on this Issue?

**Comment by Ollie42** [comment]
Found somethimg that worked for me. I used the Button "LDAP Group Mapping"
instead of the Link "mapping LDAP groups to Graylog roles".
This will open a Page where you can assign the Groups read from LDAP to
Groups found in Graylog. If no LDAP Groups are shown here there is probably something
wrong with the Group Search Pattern in the Settings of "4. Group Mapping".
Hope this helps.

Regards,
ollie

**Comment by edmundoa** [comment]
@Ollie42 thank you! That definitely helps and a broken link may explain the problem. We will investigate.
